/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppMatchesRouteImport } from './routes/app.matches'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppWorkspaceRouteImport } from './routes/app.workspace'
import { Route as AppChatIndexRouteImport } from './routes/app.chat.index'
import { Route as AppChatMatchIdRouteImport } from './routes/app.chat.$matchId'
import { Route as AppFranchiseIndexRouteImport } from './routes/app.franchise.index'
import { Route as AppFranchiseIdRouteImport } from './routes/app.franchise.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatMatchIdRoute = AppChatMatchIdRouteImport.update({
  id: '/chat/$matchId',
  path: '/chat/$matchId',
  getParentRoute: () => AppRoute,
} as any)
const AppFranchiseIndexRoute = AppFranchiseIndexRouteImport.update({
  id: '/franchise/',
  path: '/franchise/',
  getParentRoute: () => AppRoute,
} as any)
const AppFranchiseIdRoute = AppFranchiseIdRouteImport.update({
  id: '/franchise/$id',
  path: '/franchise/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$matchId': typeof AppChatMatchIdRoute
  '/app/franchise/$id': typeof AppFranchiseIdRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/franchise/': typeof AppFranchiseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$matchId': typeof AppChatMatchIdRoute
  '/app/franchise/$id': typeof AppFranchiseIdRoute
  '/app/chat': typeof AppChatIndexRoute
  '/app/franchise': typeof AppFranchiseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$matchId': typeof AppChatMatchIdRoute
  '/app/franchise/$id': typeof AppFranchiseIdRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/franchise/': typeof AppFranchiseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/discover'
    | '/app/matches'
    | '/app/profile'
    | '/app/workspace'
    | '/app/'
    | '/app/chat/$matchId'
    | '/app/franchise/$id'
    | '/app/chat/'
    | '/app/franchise/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/discover'
    | '/app/matches'
    | '/app/profile'
    | '/app/workspace'
    | '/app'
    | '/app/chat/$matchId'
    | '/app/franchise/$id'
    | '/app/chat'
    | '/app/franchise'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/discover'
    | '/app/matches'
    | '/app/profile'
    | '/app/workspace'
    | '/app/'
    | '/app/chat/$matchId'
    | '/app/franchise/$id'
    | '/app/chat/'
    | '/app/franchise/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches': {
      id: '/app/matches'
      path: '/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$matchId': {
      id: '/app/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/app/chat/$matchId'
      preLoaderRoute: typeof AppChatMatchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/franchise/': {
      id: '/app/franchise/'
      path: '/franchise'
      fullPath: '/app/franchise/'
      preLoaderRoute: typeof AppFranchiseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/franchise/$id': {
      id: '/app/franchise/$id'
      path: '/franchise/$id'
      fullPath: '/app/franchise/$id'
      preLoaderRoute: typeof AppFranchiseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatMatchIdRoute: typeof AppChatMatchIdRoute
  AppFranchiseIdRoute: typeof AppFranchiseIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppFranchiseIndexRoute: typeof AppFranchiseIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppProfileRoute: AppProfileRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatMatchIdRoute: AppChatMatchIdRoute,
  AppFranchiseIdRoute: AppFranchiseIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppFranchiseIndexRoute: AppFranchiseIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
